### 1.ndarray 성능확인


In [ ]:
# [1] numpy Vectorizing 연산 원리 - Python with Loop
A = [1, 2, 3]
B = [4, 5, 6]
C = []
for a, b in zip(A, B):
  C.append(a + b)

print(C)

In [1]:
# [2] numpy Vectorizing 연산 원리 - Python with Numpy
import numpy as np
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
C = A + B
print(C)

[5 7 9]


In [3]:
# [3] numpy와 list의 성능 차이 확인을 위한 함수 작성
# a 1000000 행, 4 열 - list
import numpy as np
a = [[ 1, 2, 3, 4 ] for _ in range(1000000)]
b = np.array(a) # ndarray

def exchange_list(a):
  c = []
  for x in a:
      x[2], x[3], x[0], x[1] = x
      c.append(x)
  return c

def exchange_ndarray(a):
   return a[ : ,[2, 3, 0, 1]]

In [4]:
# [4] a, b 배열의 확인
print(a[:2], b[:2], sep='\n')

[[1, 2, 3, 4], [1, 2, 3, 4]]
[[1 2 3 4]
 [1 2 3 4]]


In [5]:
# [5] numpy와 list의 성능 차이 확인을 위한 함수 실행
c = exchange_list(a)
d = exchange_ndarray(b)
print(c[:2], d[:2], sep='\n')

[[3, 4, 1, 2], [3, 4, 1, 2]]
[[3 4 1 2]
 [3 4 1 2]]


In [6]:
# [6] list를 사용했을 때의 성능 확인
%timeit exchange_list(a)

75.8 ms ± 4.33 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [7]:
# [7] numpy 배열을 사용했을 때의 성능 확인
%timeit exchange_ndarray(b)

7.35 ms ± 714 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
# [8-1] 데이터에 비해 준비한 메모리가 작다
a = np.array([178,216,128,427,500], dtype=np.int8 )
print(a.ndim, a.shape, a.dtype)
print(a)

# [8-2] 데이터에 크기에 맞춘 메모리 사용
a = np.array([178,216,128,427,500], dtype=np.int16 )
print(a.ndim, a.shape, a.dtype)
print(a)

In [8]:
# [9] numpy method 요약
A=np.array([[[12,25,34,21],[345,23,13,622]],[[12,25,34,21],[345,23,13,622]]])
print(A.shape,A.ndim,A.dtype,A.size,A.itemsize,A.strides)

(2, 2, 4) 3 int32 16 4 (32, 16, 4)


In [9]:
# [10] print array information
def printInfo(a):
    data = ['a.ndim', 'a.shape', 'a.size', 'a.dtype', 'a.itemsize', 'a.strides']
    for x in data:
        print('%-11s' % x, eval(x))

a = np.array([[0,1,2,3],[3,4,5,16]], dtype=np.int32) #한 정수당 4바이트(1바이트당 8비트)
printInfo(a)
#print(a.ndim, a.shape, a.size, a.dtype, a.itemsize, a.strides)

a.ndim      2
a.shape     (2, 4)
a.size      8
a.dtype     int32
a.itemsize  4
a.strides   (16, 4)


##### 2) np.arange 사용

In [10]:
def printary(*a):
    for x in a:
        print(f'{type(x)}\n{x.dtype}\n{x}', end='\n\n')

    print("-" * 30)

In [11]:
# [11] np.arange의 사용
# np.arange(stop:number, dtype=None)
# np.arange(start, stop)
# np.arange(start, stop, step)
a = np.arange(5)
b = np.arange(1, 10, 2)
c = np.arange(1, 2, 0.1) #, dtype=np.float64)
printary(a, b, c)

<class 'numpy.ndarray'>
int32
[0 1 2 3 4]

<class 'numpy.ndarray'>
int32
[1 3 5 7 9]

<class 'numpy.ndarray'>
float64
[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]

------------------------------


##### 3) np.linspace 사용

In [ ]:
# [12] np.linspace(start:array_like, stop, num=50, endpoint=True, retstep=False, dtype=None)
a = np.linspace(1, 5, 9) # 1~5사이 9개 숫자(5포함)
b = np.linspace(1, 5, 10, endpoint=False) # 1부터 5까지 10개 및 마지막 숫자 미포함
c,d = np.linspace(1, 5, 9, retstep=True) # d는 step임
print(a, b, c,d, sep="\n")

##### 4) random 사용

In [ ]:
# [13] numpy 출력 옵션 조절
np.set_printoptions(threshold=999, # 999개까지는 생략없이 보여줘라
                    suppress=True, # 소수점 표현
                    precision=4,   # 소수점 4자리까지
                    edgeitems=3)   # 생략했다면 위아래왼오 3칸까지는 보여줘

In [13]:
# [14]배열 출력 함수
def printary(*a):
    for x in a :
        print(f"shape : {x.shape}")
        print(f"array : %s{x} " % ('' if x.ndim == 1 else '\n'))
        print("mean  : %.3f, std : %.3f" % (x.mean(), x.std()))
        print("-" * 30)

In [ ]:
# [15] np.random.rand(d0, d1, ...,dn)
# 0~1 사이의 균일 분포로 실수 난수 배열 생성
# d0, d1, ..., dn : 배열의 shape을 의미하는 정수
a = np.random.rand(5) # 0~1사이 양수값, 균일분포
b = np.random.rand(2, 2, 3) # rand는 n차원
printary(a, b)

In [ ]:
# [16] np.random.randint(e, size=n)
# np.random.randint(s, e, size=n)
# 0~e-1, s~e-1 범위의 값을 갖는 균일 분포의 정수 난수 생성
# size : 정수(1차원), tuple(1차원 이상)로 shape 지정
a = np.random.randint(10, size=(5,))
b = np.random.randint(50, 100, (2,4))
printary(a, b)

In [ ]:
# [17] np.random.randn(d0, d1, ... dn)
# 평균 0, 표준편차 1을 갖는 가우시안 표준 정규 분포로 난수 배열 생성(음수 포함)
a = np.random.randn(5) #정규분포
b = np.random.randn(2, 5,3) #차원 rand랑 비슷함
printary(a, b)

In [ ]:
# [18] np.random.normal(평균, 표준편차, size)
# 생략하면 평균=0, 표준편차=1, size=1이 됨
a = np.random.normal(2, 3, (100, 20)) # 평균, 표준편차, 사이즈  <-> randint는 시작,끝,사이즈
printary(a)

In [14]:
# [19] permutation 사용 배열 생성
#np.random.permutation(e) : 0 ~ e-1 값을 갖는 정수의 무작위 순서 1차원 배열 생성
#np.random.permutation(c) : c 요소들에 대해 무작위 순서로 변경된 1차원 배열 생성
# e : 정수, c : array_like 객체
a = np.random.permutation(10)
data = np.array([1,3,4,5,3,1,3])
b = np.random.permutation(data)
mylist = [[1,2,3],[4,5,6],[7,8,9],[3,2,1]]
c = np.random.permutation(mylist)
printary(a, b, c)

shape : (10,)
array : [7 3 9 1 4 0 5 6 2 8] 
mean  : 4.500, std : 2.872
------------------------------
shape : (7,)
array : [3 1 3 1 4 3 5] 
mean  : 2.857, std : 1.355
------------------------------
shape : (4, 3)
array : 
[[1 2 3]
 [3 2 1]
 [4 5 6]
 [7 8 9]] 
mean  : 4.250, std : 2.618
------------------------------


##### 5) 특정값으로 채워진 ndarray생성

In [ ]:
def printary(*a):
    for x in a:
        print(f'{x.dtype}\n{x}')
    print("-" * 30)

In [ ]:
# [20] np.zeros(shape, dtype=float64)
#shape: 정수(1차원), tuple(1차원 이상)
a = np.zeros(10, dtype = np.int32)
b = np.zeros(mshape)
printary(a, b)

In [ ]:
# [21] np.empty(shape, dtype=float64)
a = np.empty(10, dtype=np.int32) # 별도로 채우기를 하지 말라
b = np.empty(mshape)
printary(a, b)

In [ ]:
# [22] np.ones(shape,dtype=float64)
#np.full(shape, value, dtype=None)
a = np.ones(mshape)
b = np.full(mshape, 5.0)
printary(a, b)

In [ ]:
# [23] np.eye(N, M=None, k=0, dtype=float64)
a = np.eye(3) # 3x3 배열 만든후 대각행렬
b = np.eye(3, 5, 2) # 3x5 배열 2칸부터 만든후 대각행렬
c = np.eye(3, 5, -1)
printary(a, b, c)

In [ ]:
# [24] np.zeros_like(array_like, dtype=None)
a = np.zeros_like([1,2,3,5])
b = np.empty_like([[1,2,3,22],[12,34,25,35]])
printary(a, b)

In [ ]:
# [25] np.ones_like, np.full_like
a = np.ones_like([[1,2,3],[4,5,6]], dtype=np.float32)
b = np.full_like(np.arange(5), 5)
printary(a, b)